### ISSUE TITLE
Adding Verovio version in the test pages

### ISSUE THREAD

**Issue by lpugin** [DDMAL/mei-test-set#4]
It would be useful to see what version of Verovio is used. It could be placed in the footer. The version can be retrieved with the .getVersion() method.

**Comment by minamouse** [comment]
When I do this, it gives me "0.9.8-df2cd92". Is that right? or is there a way to get only the 0.9.8 part?

**Comment by lpugin** [comment]
This is right. There is no way not to get the commit number.

**Comment by minamouse** [comment]
Ok, great!
